(executable
 (name preprocessing_worker)
 (libraries modelkit))

(executable
 (name linear_models_worker)
 (libraries modelkit))

(executable
 (name ridge_classifier_worker)
 (libraries modelkit))

(executable
 (name multinomial_logistic_worker)
 (libraries modelkit))

(executable
 (name glm_worker)
 (libraries modelkit))

(executable
 (name regularized_linear_worker)
 (libraries modelkit))

(executable
 (name sgd_regressor_worker)
 (libraries modelkit))

(executable
 (name sgd_classifier_worker)
 (libraries modelkit))

(executable
 (name splitters_worker)
 (libraries modelkit))

(executable
 (name metrics_worker)
 (libraries modelkit))

(executable
 (name cross_validation_worker)
 (libraries modelkit))

(executable
 (name grid_search_worker)
 (libraries modelkit))

(executable
 (name parallel_cross_validation_worker)
 (libraries modelkit modelkit-parallel))

(executable
 (name adapter_admission_worker)
 (enabled_if
  (<> %{os_type} Win32))
 (libraries modelkit modelkit-nx modelkit-talon nx talon unix))

(executable
 (name sparse_kernels_worker)
 (libraries modelkit unix))
