(library
 (name modelkit_talon)
 (public_name modelkit-talon)
 (modules modelkit_talon)
 (libraries modelkit talon nx nx.buffer))

(test
 (name modelkit_talon_test)
 (modules modelkit_talon_test)
 (package modelkit-talon)
 (libraries
  modelkit
  modelkit-talon
  modelkit_test_support
  talon
  nx
  alcotest
  str))
