(library
 (name modelkit_parallel)
 (public_name modelkit-parallel)
 (modules modelkit_parallel)
 (libraries modelkit domainslib))

(test
 (name modelkit_parallel_test)
 (modules modelkit_parallel_test)
 (package modelkit-parallel)
 (libraries modelkit modelkit-parallel alcotest))

(test
 (name learning_curve_parallel_test)
 (modules learning_curve_parallel_test)
 (package modelkit-parallel)
 (libraries modelkit modelkit-parallel alcotest))

(test
 (name evaluation_metadata_parallel_test)
 (modules evaluation_metadata_parallel_test)
 (package modelkit-parallel)
 (libraries modelkit modelkit-parallel modelkit_test_support alcotest))

(test
 (name transformed_target_parallel_test)
 (modules transformed_target_parallel_test)
 (package modelkit-parallel)
 (libraries modelkit modelkit-parallel modelkit_test_support alcotest))

(test
 (name resampling_parallel_test)
 (modules resampling_parallel_test)
 (package modelkit-parallel)
 (libraries modelkit modelkit-parallel modelkit_test_support alcotest))

(test
 (name partitioning_parallel_test)
 (modules partitioning_parallel_test)
 (package modelkit-parallel)
 (libraries modelkit modelkit-parallel modelkit_test_support alcotest))

(test
 (name randomized_search_parallel_test)
 (modules randomized_search_parallel_test)
 (package modelkit-parallel)
 (libraries modelkit modelkit-parallel modelkit_test_support alcotest))

(test
 (name halving_parallel_test)
 (modules halving_parallel_test)
 (package modelkit-parallel)
 (libraries modelkit modelkit-parallel modelkit_test_support alcotest))

(test
 (name checkpoint_parallel_test)
 (modules checkpoint_parallel_test)
 (package modelkit-parallel)
 (libraries modelkit modelkit-parallel modelkit_test_support alcotest))
