(library
 (name modelkit_parallel)
 (public_name modelkit-parallel)
 (modules modelkit_parallel)
 (libraries modelkit domainslib))

(test
 (name modelkit_parallel_test)
 (modules modelkit_parallel_test)
 (package modelkit-parallel)
 (libraries modelkit modelkit-parallel alcotest))

(test
 (name evaluation_metadata_parallel_test)
 (modules evaluation_metadata_parallel_test)
 (package modelkit-parallel)
 (libraries modelkit modelkit-parallel modelkit_test_support alcotest))

(test
 (name transformed_target_parallel_test)
 (modules transformed_target_parallel_test)
 (package modelkit-parallel)
 (libraries modelkit modelkit-parallel modelkit_test_support alcotest))
